import React from 'react'

export default function App() {
    //Holds an array of all submitted tasks
    const [formDataList, setFormDataList] = React.useState([]);

    //Append the newTask as an object to this array when each time the form is submitted
    function addTask(e){
        const fields= ["selectCategory", "taskname", "datename", "descriptionname"]
        const newTask = {}; // will become one row
        fields.forEach(field=> {
                const value = e.get(field)?.trim(); // string or null
                newTask [field]= value? value: null // ternary: keep "" if missing
            })
        // Append to previous list
        setFormDataList(formDataList=>
            [...formDataList, newTask])
    }

    const today = new Date().toISOString().split("T")[0];

    //Table rows are generated by .map() over
    function formDate() {
        return formDataList.map((item,index) => (
        <tr key={index}>
            <td>{item.selectCategory}</td>
            <td>{item.taskname}</td>
            <td>{item.datename}</td>
            <td>{item.descriptionname}</td>
        </tr>
    ))
    }

    return (
        <div className="container">
            <h2>To Do List</h2>
            <h3>Add To-Do</h3>
            <form className="inputForm" action={addTask}>
                <label htmlFor="catagory-select"></label>
                    <select
                        /*id="selectCategory" <label> only applies on <input>*/
                        name="selectCategory"
                        className="category-select"
                        defaultValue="category"
                        >
                        <option value="">Category</option>
                        <option value="work">Work</option>
                        <option value="family">Family</option>
                        <option value="personal">Me</option>
                    </select>
                <label htmlFor="taskname"></label>
                    <input
                        id="taskname"
                        name="taskname"
                        type="text"
                        placeholder="Add task"
                    />
                <label htmlFor="datename"></label>
                    <input
                        id="datename"
                        name="datename"
                        type="date"
                        defaultValue={today}
                    />
                <label htmlFor="descriptionname"></label>
                    <textarea
                        id="descriptionname"
                        name="descriptionname"
                        rows="4"
                        placeholder="Add description"
                    ></textarea>
                <button className="submit-btn">Confirm</button>
            </form>
            <h3> Submitted To-do </h3>
            <div className="outputForm">
                <table>
                    <thead>
                    <tr>
                        <th>Category</th>
                        <th>Task</th>
                        <th>Date</th>
                        <th>Description</th>
                    </tr>
                    </thead>
                    <tbody>
                        {formDate()}
                    </tbody>
                </table>
                <button
                    className="delete-btn"
                    onClick={() => setFormDataList([])}
                    type="button"
                >
                    Delete All
                </button>
            </div>
        </div>
  )
}
